2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_setup.py:_flush():67] Configure stats pid to 73365
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_setup.py:_flush():67] Loading settings from /Users/gracekim/.config/wandb/settings
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_setup.py:_flush():67] Loading settings from /Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/wandb/settings
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/wandb/run-20250303_153354-gqagoqzf/logs/debug.log
2025-03-03 15:33:54,614 INFO    MainThread:73365 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/wandb/run-20250303_153354-gqagoqzf/logs/debug-internal.log
2025-03-03 15:33:54,615 INFO    MainThread:73365 [wandb_init.py:init():761] calling init triggers
2025-03-03 15:33:54,615 INFO    MainThread:73365 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-03 15:33:54,615 INFO    MainThread:73365 [wandb_init.py:init():784] starting backend
2025-03-03 15:33:54,615 INFO    MainThread:73365 [wandb_init.py:init():788] sending inform_init request
2025-03-03 15:33:54,639 INFO    MainThread:73365 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-03 15:33:54,639 INFO    MainThread:73365 [wandb_init.py:init():803] backend started and connected
2025-03-03 15:33:54,641 INFO    MainThread:73365 [wandb_init.py:init():896] updated telemetry
2025-03-03 15:33:54,662 INFO    MainThread:73365 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 15:33:55,304 INFO    MainThread:73365 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 15:33:55,367 INFO    MainThread:73365 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 15:33:55,367 INFO    MainThread:73365 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 15:33:55,367 INFO    MainThread:73365 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 15:33:55,367 INFO    MainThread:73365 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 15:33:55,373 INFO    MainThread:73365 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 15:33:55,377 WARNING MsgRouterThr:73365 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/.venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/.venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/.venv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/.venv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gracekim/Documents/School_Everything_and_LEARNING/Stanford/Githubs/loc-gsopt/.venv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 15:33:55,379 INFO    MsgRouterThr:73365 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
